version: '3.9'
services:
  another_maria_test:
    container_name: another_maria_test
    # command: yarn docker-develop
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - another_maria_test_mariadb
    volumes:
      - .:/app
      - ./src/public:/app/dist/public
      - ./src:/app/src
      - ./dist:/app/dist


  another_maria_test_mariadb:
    container_name: another_maria_test_mariadb
    image: mariadb:10.5.13
    restart: always
    ports:
      - ${DB_PORT}:3306
    volumes:
      - another_maria_test:/data/db_another_maria_test_mariadb
    environment:
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}

volumes:
 another_maria_test: {}
